name: Code Formatting
on: [push, pull_request, workflow_dispatch]
jobs:
  code_formatting:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: TOUCH
      run: date > date.file
    - name: Loop
      run: |
         for (( i=0; i <=5; i++))
         do
             ls -lha /blabhlh
             if [ $? -eq 0 ]; then
                 break
             fi
         done
    - name: Unnecessary file
      run: echo "some file" > some_file
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.8
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Replaced foo with bar at `date`
