name: Code Formatting
on: [push, pull_request, workflow_dispatch]
jobs:
  code_formatting:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
    - name: LS
      run: ls -lha .
    - name: TOUCH
      run: touch some_filename
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.8
      with:
        commit_message: Replaced foo with bar
